### ISSUE TITLE
requiredOrgs for private repos

### ISSUE THREAD

**Issue by nguyenchr** [facebook/mention-bot#104]
Hey it seems that github only returns public org memberships for a user (regardless of the authenticated user) https://developer.github.com/v3/orgs/#list-user-organizations

This is particularly difficult for private repos as this means most users will be filtered out unless they have publicly listed the org membership

The downside to this is that leaving `requiredOrgs` empty generally ends up notifying a bunch of people who are no longer part of the org

I was thinking we could use the https://developer.github.com/v3/orgs/members/#members-list call to get all the members for that org and use that for filtering instead

**Comment by nguyenchr** [comment]
also happy to make the fix, just wanted to get some feedback as to whether this is a good way forward

**Comment by vjeux** [comment]
I didn't write this feature so I don't know much about it. If you could ping the person that did to get context that would be great. Otherwise if you have a pull request that fixes the problem, i'd be glad to take it

**Comment by nguyenchr** [comment]
@vjeux no problem, I'll get onto it!
