### ISSUE TITLE
patent grant?

### ISSUE THREAD

**Issue by freakabcd** [facebook/mention-bot#11]
At tne end of the README, in the License section, you have:

``mention-bot is BSD-licensed. We also provide an additional patent grant.``

What is this patent grant you mention?

**Comment by vjeux** [comment]
This is the patent file: https://github.com/facebook/mention-bot/blob/master/PATENTS

For more context on this, I recommend reading this post which explains what it does and why we put it there: https://code.facebook.com/posts/1639473982937255/updating-our-open-source-patent-grant/
