### ISSUE TITLE
Customized message in the config file (.mention-bot)?

### ISSUE THREAD

**Issue by hunkim** [facebook/mention-bot#111]
To customize msg, we need to modify the code: 
```
module.exports = function(
  reviewers: Array<string>,
  mentionSentenceBuilder: (reviewers: Array<string>) => string,
  defaultMessageGenerator: (reviewers: Array<string>) => string
): string {

  // This file is a place where you can change the way the message the bot
  // uses to comment. For example:
  //
  //   return 'Please review this ' + mentionSentenceBuilder(reviewers);
  //
  // will print
  //
  //   Please review this @georgecodes and @vjeux

	return defaultMessageGenerator(reviewers);
};
```
It's simple enough, but requres to run their own bot servers.

Why don't we just add it in the config file (.mention-bot)?
```
{
  "maxReviewers": 5, // Maximum  number of people to ping in the PR message, default is 3
  "numFilesToCheck": 10, // Number of files to check against, default is 5
  "message": "'Please review this @reviwers",
...
}
```

**Comment by vjeux** [comment]
Because the handling of the message involves pluralization and english thing like "and". But I agree that would be nice to have a small config like this if you don't intend to change it dramatically

**Comment by hunkim** [comment]
I'll try to come up with a PR (with a minimal change). :-)

**Comment by hunkim** [comment]
@vjeux, I put some thoughts. First, we can remove pluralization -- keep it simple. So the conf file would be:
  ```
  {
      "maxReviewers": 5, // Maximum  number of people to ping in the PR message, default is 3
      "numFilesToCheck": 10, // Number of files to check against, default is 5
       // Or other nice phrase without pluralization 
     "message": "@pullRequester, thanks! @reviwers, please review this.",
     ...
   }
```
In the code, we just replace '@pullRequester' and '@reviwers'. Very simple.

The second way is implementing the pluralization getting /singular/plural/ words. For example, the message would be:

`"message": "we identified @reviwers to be /a// potential /reviewer/reviwers/.",  `

Based on the reviewers.length, we choose the first or second word. Doable, but complicated perhaps for the users.

Any thoughts?

**Comment by vjeux** [comment]
first one seems simpler and likely going to solve the problem
