### ISSUE TITLE
.mention-bot file not being read?

### ISSUE THREAD

**Issue by lilnate22** [facebook/mention-bot#117]
I have a `.mention-bot` file that has the following:

     "actions": ["opened", "synchronize"] // List of PR actions that mention-bot will listen to, default is "opened"
}

however, it seems the file is not being loaded, as it ignores PR with syncronize (info message and all)

also the message that gets posted is different from the one listed in `.mention-bot`

**Comment by brupm** [comment]
Look for syntax error in the json, had that happen to me. The error message doesn't make that clear.

**Comment by lilnate22** [comment]
unfortunately that does not seem to be it.

```
{
  "maxReviewers": 5,
  "numFilesToCheck": 10,
  "message": "@pullRequester, thanks! @reviewers, please review this.",

  "alwaysNotifyForPaths": [
    {
      "name": "ghuser",
      "files": ["**/*.less"]
    }
  ],
  "fallbackNotifyForPaths": [
    {
      "name": "ghuser",
      "files": ["**/*.less"]
    },
{
  "name": "ghuser",
   "files": ["**/sear*/*.js"]
},
{
 "name": "ghuser",
  "files": ["**/prof*/*.js"]
}
  ],
  "findPotentialReviewers": false,
  "userBlacklist": [],
  "userBlacklistForPR": [],
  "requiredOrgs": [],
  "actions": ["opened", "synchronize"]
}
```

is valid according to my parser....but mention-bot doesn't seem to care, since the message it posted doesnt have the custom message as above.

**Comment by hunkim** [comment]
@lilnate22 I am not sure the running bot is using the current master version. @vjeux , can you verify?

**Comment by lilnate22** [comment]
So here is what i did:

Git clone repo, vi .mention-bot  

(then I use pm2 to start mentionbot)


according to README, that should be it right?

**Comment by vjeux** [comment]
Should be good

```
(511) >> git push heroku master
Everything up-to-date
```

**Comment by lilnate22** [comment]
@vjeux  i am not using the heroku.

i tested on /23 and it didnt even use the message on .mention

**Comment by hunkim** [comment]
@lilnate22 Any luck? I think we should add `console.log` to check the configration and `.mention.bot` file.

**Comment by lilnate22** [comment]
@hunkim  nope. no luck. I added the file params manually to server.js default.

but the mention-bot config file is not being read at all (evident by the fact the custom message is not getting displayed)

**Comment by mlbright** [comment]
The sample config file has comments in it. JSON parsers often can't handle comments, and I think this is the case here. Try removing all the comments from your `.mention-bot` file.

**Comment by hunkim** [comment]
@mlbright I noticed this too. I think we need to remove comments in the example config file. Also, we may need to capture the JSON parsing error and log it.

**Comment by lilnate22** [comment]
sorry fellas i already did remove the comments, and as far as i can tell it passes json validators

**Comment by lilnate22** [comment]
`{
  "maxReviewers": 5,
  "numFilesToCheck": 10,
  "message": "@pullRequester, thanks! @reviewers, please review this.",

  "alwaysNotifyForPaths": [
    {
      "name": "ayjee",
      "files": ["**/*.less"]
    }
  ],
  "fallbackNotifyForPaths": [
    {
      "name": "ghuser",
      "files": ["**/*.less"]
    },
{
  "name": "ghuser",
   "files": ["**/sear*/*.js"]
},
{
 "name": "ghuser",
  "files": ["**/prof*/*.js"]
}
  ],
  "findPotentialReviewers": true,
  "userBlacklist": [],
  "userBlacklistForPR": [],
  "requiredOrgs": [],
  "actions": ["opened", "synchronize"]
}`


@mlbright  @hunkim  my .mention-bot file is listed here, passes json validators on my end

**Comment by vjeux** [comment]
I'm sorry but I don't have the time to help you investigate what is going wrong :( I'm going to close down this issue, but feel free to keep posting here and others to help out.
