### ISSUE TITLE
Only activate mention bot on PRs without comments

### ISSUE THREAD

**Issue by erlend-sh** [facebook/mention-bot#119]
We've been testing Mention bot for discourse/discourse and we're enjoying it. But I think the bot is a bit quick to spring into action. Most PR's will have eyes on it within 48 hours, so the extra mention will oftentimes be redundant. I was wondering if it'd be possible to have a configuration that makes it so that:

Bot will not mention developers unless:

- PR is 3 days old AND
- PR has not yet been commented on by any ORG member

If sorting for ORG members is too tricky then just "has not yet received X comments" could work too, but it needs to be configurable since some projects, like ours, have other bots such as a CLA bot that will post on every single issue.

**Comment by hunkim** [comment]
It's a good idea, but current mention bot acts on the PR hook. To implement this, I guess we need a server to periodically check PR status.  @vjeux, are there any simple ways to implement this?

**Comment by vjeux** [comment]
I'm happy to accept this if you implement it, but I'm not going to myself :)

**Comment by vjeux** [comment]
@hunkim yeah, would need to build some sort of cron that checks if the pr is old, not been checked yet and has no comments from the org owner and then use the cli api for the bot to run it

**Comment by vjeux** [comment]
Also note that the bot checks the blame against master, so if you do it a week after, it is probably going to return incorrect results. A safer solution would be to run the bot instantly and store the people that it would have mentioned and then x days after, comment with those people.

**Comment by erlend-sh** [comment]
Thanks for all the input! It sounds like the periodic checks would be the hardest part to this. Perhaps an acceptable trade-off could be:

- Run the bot upon each new PR and store the reply, like @vjeux described.
- After 3 days, check status of PR. If status is OPEN, mention-bot will comment.

**Comment by vjeux** [comment]
What you are asking for is pretty easy. I'm sure that you can get it working if you spend an hour or two

**Comment by hunkim** [comment]
@erlend-sh it's a good idea. You may use https://www.npmjs.com/package/node-schedule to implement the "After 3 days..." part.

**Comment by saiqulhaq** [comment]
I'm working on a PR for this; would you mind just telling me if I'm on the right path here?
This is [my working branch](https://github.com/saiqulhaq/mention-bot/tree/delayedJob) for this issue

**Comment by erlend-sh** [comment]
Done in #132

**Comment by akshay0110** [comment]
thanks For Sharing this Article <a href="http://learnhax.net/activate-facebook-bot-comments/">ACTIVATE FACEBOOK BOT COMMENTS ON FACEBOOK</a>, Its a cool trick.
