### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by Schniz** [facebook/mention-bot#12]
that would be nice :santa:

**Comment by papucho** [comment]
That would be awesome!

**Comment by vjeux** [comment]
I have no plans for implementing it but will accept a pull request :)

**Comment by Schniz** [comment]
Great👍🏻
Hope I'll have free time tomorrow

**Comment by vjeux** [comment]
I'm closing this for now since I'm not going to work on it. But feel free to open a pull request if you get it working :)
