### ISSUE TITLE
Feature Request: Skip PR based on Title

### ISSUE THREAD

**Issue by mattpickle** [facebook/mention-bot#121]
## Configuration 

*.mention-bot*
```
{
  "skipTitle": "WIP"
}
```

Using the above configuration (or something similar) would not mention reviewers if the PR Title contains **WIP**.

**Comment by vjeux** [comment]
Would be useful! Happy to merge this if you send a pull request

**Comment by hansott** [comment]
Would like to implement it! What about a regex as config value?

**Comment by mattpickle** [comment]
@hansott Regex would be cool too.  Would be overkill for what we plan to use, but I could definitely see the use.

**Comment by hansott** [comment]
We use labels for "QA", "Work in progress", ... etc. Skip PR's with specific labels could also be an option?

**Comment by hunkim** [comment]
IMHO, a simple keyword in the title would be a good start. Let's keep it simple. :-)

**Comment by hunkim** [comment]
@mattpickle Please let me know if you need any help on this. I think it's a simple change.

**Comment by KrishMunot** [comment]
@hunkim I would love to take point for this issue and would appreciate any sort of help. :)

**Comment by mattpickle** [comment]
@KrishMunot I'm cool with that.  Haven't had a chance to start yet.

**Comment by hunkim** [comment]
@KrishMunot Cool! I think you can start with the configuration in server.js:

```python
  // default config
  var repoConfig = {
    maxReviewers: 3,
    numFilesToCheck: 5,
    userBlacklist: [],
    userBlacklistForPR: [],
    userWhitelist: [],
    fileBlacklist: [],
    requiredOrgs: [],
    findPotentialReviewers: true,
    actions: ['opened'],
    skipAlreadyAssignedPR: false,
  };

  try {
    // request config from repo
    var configRes = await getRepoConfig({
      user: data.repository.owner.login,
      repo: data.repository.name,
      path: CONFIG_PATH,
      headers: {
        Accept: 'application/vnd.github.v3.raw'
      }
    });

    repoConfig = {...repoConfig, ...JSON.parse(configRes)};
```
Then, before bot fires the comment, add one if condition based on the condifuration:

```python
github.issues.createComment({
    user: data.repository.owner.login, // 'fbsamples'
    repo: data.repository.name, // 'bot-testing'
    number: data.pull_request.number, // 23
    body: message
  });
```

I gues that's it. Look forward to your beautiful PR.

@vjeux, please correct me if I miss something.

**Comment by KrishMunot** [comment]
Thanks, @hunkim , I just made a PR [here](https://github.com/facebook/mention-bot/pull/125). 
Do you mind reviewing it?

**Comment by vjeux** [comment]
It's in, thanks @mattpickle !
