### ISSUE TITLE
Don't mention if PR author is a project-member

### ISSUE THREAD

**Issue by erlend-sh** [facebook/mention-bot#124]
It'd be nice to have a setting for the following.

If a project owner or collaborator is the one submitting a PR, mention-bot should remain silent. Something like:

```
{
"skipCollaboratorPR": true
}
```

Here's an example of such an unwanted scenario:

https://github.com/discourse/wp-discourse/pull/197

In many projects it should be safe to assume that a collaborator knows the project well enough to dish out mentions themselves if need be.

**Comment by vjeux** [comment]
Sounds like a great idea indeed. I'd take it if you send a pull request

**Comment by erlend-sh** [comment]
Great. I'm talking to a dev who might be able to help out.

**Comment by erlend-sh** [comment]
Done in #132
