### ISSUE TITLE
Feature request: non-repository specific blocklist

### ISSUE THREAD

**Issue by tractorcow** [facebook/mention-bot#126]
If I don't want someone to talk to me, I don't want to have to declare where they are not allowed to talk to me; I simply want that user to know that I don't want to mentioned in ANY context.

> The bot can be configured by adding a .mention-bot file to the base directory of the repo.

The problem with this is that I have to declare this everywhere I have ever made a commit.

Can we please have some kind of global ignore list that mention-bot draws from, even if that's another (single) repo somewhere? I'm a maintainer of over a hundred repositories and I'd like to opt out of any further mentions. I would much rather make a single pull request to opt out than a hundred.

Might I suggest a separate repo at https://github.com/facebook/mention-bot-blocklist that individual users can request pulls to? The bot could refer to both the root .mention-bot file on this repo, as well as the repo it's currently acting on.

A shout out to the great developers who make a tool that's useful to many people (even though it's not useful to me! :D).

**Comment by vjeux** [comment]
Hey! This is absolutely a legitimate concern. As with any bot that sends email notifications, there should be a way to turn it off.

I've been thinking about many ways to achieve this:
- as you suggested, a git repo where you can send a pull request. The issue with this is that it's a lot of steps to unsubscribe. Ideally i'd like it to be a one click operation.
- a website where you can unsubscribe. The issue here is that we would need to get you to log in which is not a very good user experience. You want to unsubscribe, logging in to do that seems sketchy.
- go to github and block the mention-bot user.

I think the last one is actually a really good solution and should be promoted in the official documentation.

Let me know what you think

**Comment by dhensby** [comment]
This is a legitimate concern - under various "CAN-SPAM" legislation there has to be a way to unsubscribe. Individually maintaining this via a committed file is a laborious way of doing so (as agreed in this thread).

The most useful thing I would imagine is a website you go to, authorise with GH and then either opt out of any mention, vendors or just individual projects.

For the time-being, blocking the user is a good stop-gap solution.

**Comment by dhensby** [comment]
Heh, I just realised that blocking the bot is only suitable for people who NEVER want to hear from the bot but not those that just don't want to from specific projects. So maybe it's not a suitable solution :/

**Comment by tractorcow** [comment]
I would go for the second option.

> a website where you can unsubscribe. The issue here is that we would need to get you to log in which is not a very good user experience. You want to unsubscribe, logging in to do that seems sketchy.

If you can simply use your github login, then the only user experience issue would be the initial permission assignment to your account. You can expect most of us would remain logged in to github most of the time anyway. :)

> This is a legitimate concern - under various "CAN-SPAM" legislation there has to be a way to unsubscribe. Individually maintaining this via a committed file is a laborious way of doing so (as agreed in this thread).

Perhaps the first time that mention-bot ever mentions a user, it also sends them an email with a single-click opt out link?

**Comment by dhensby** [comment]
How could mention bot email you? Inspect the commits? Some might be no reply email addresses, especially on public repos. 

Mention bot doesn't email themselves, it's through GH notifications, isn't it?

**Comment by tractorcow** [comment]
> Mention bot doesn't email themselves, it's through GH notifications, isn't it?

I'm not sure, but I guess it would have to be via github.

**Comment by vjeux** [comment]
I've added a repo called <strong>how-to-unsubscribe</strong> on the mention-bot account. It should fix your use case. If the project gets a wider adoption, we'll probably want to invest in more fine-grained control but that is out of scope for me now.

<img width="636" alt="screen shot 2016-05-25 at 12 38 55 pm" src="https://cloud.githubusercontent.com/assets/197597/15553794/ab9a6e08-2275-11e6-9239-d2b64c2a0480.png">

https://github.com/mention-bot/how-to-unsubscribe

<img width="995" alt="screen shot 2016-05-25 at 12 39 23 pm" src="https://cloud.githubusercontent.com/assets/197597/15553806/ba3d2338-2275-11e6-8c38-951a66b28593.png">

**Comment by dhensby** [comment]
Thanks for that @vjeux 

Though it doesn't solve the following two scenarios:

- Projects want 3 _useful_ members of the team mentioned
- Users want to be mentioned on some projects but not others

**Comment by vjeux** [comment]
For 1), I'd recommend adding a setting in mention-bot to filter people you want.

For 2), yeah it's unfortunate. We'd need something more sofisticated that I won't have the time to work on anytime soon.

**Comment by dhensby** [comment]
> I'd recommend adding a setting in mention-bot to filter people you want.

I wasn't aware this was possible, but we want to avoid adding `.mention-bot` files to all our repos and the overhead that comes with keeping those consistent over 80 repositories.

I/we don't expect this to be added or sorted immediately, but we do want to raise it as a concern.

We'll look at running our own bot where we automatically set some of the standard filters.

**Comment by tractorcow** [comment]
Thanks @vjeux, I'm happy with this resolution. :) I agree that fine-grained control can be a nice end goal, but is not necessary to solve the problem I initially raised.
