### ISSUE TITLE
Add support for language detection

### ISSUE THREAD

**Issue by rebornix** [facebook/mention-bot#133]
We are maintaining popular projects, there might be non-English speakers come to the repo and file issues using French, Spanish, German, Italian, CJK, etc to describe their problems. Of course we should encourage users to translate their issues before posting, but this problem always happens. So I'm thinking if there is any chance that we can add language detection to mention-bot and add a separate configuration, let's say

```
languages: {
  CJK: user_name
}
```

Then people on the list can be notified and help solve it.

**Comment by vjeux** [comment]
Mention bot works only on pull requests and analyze the blame to figure out who should be reviewing it. I have a lot of ideas for how to deal with issues but this is out of scope for this project.

I would encourage you to start your own bot and do that. It shouldn't be very difficult to implement and has the potential to be highly impactful!
