### ISSUE TITLE
Is mention-bot account alive?

### ISSUE THREAD

**Issue by jihungen** [facebook/mention-bot#134]
I found that the mention-bot is very useful. So, I have investigated the mention-bot for research purpose. I checked the PRs that the mention-bot helped to identify the reviewers.

However, all the messages generated by mention-bot account (www.github.com/mention-bot) disappeared since yesterday. As far as I know, this project also uses mention-bot account (www.github.com/mention-bot) to identify the reviewers.

Does the mention-bot account have any problem? Or do you change your policy?

Thank you!

**Comment by wkentaro** [comment]
same problem.

**Comment by domenkozar** [comment]
cc @vjeux

**Comment by vjeux** [comment]
Grrr, must have been caught again by github bot detection. I'll re-submit a request when I get back home.

**Comment by aspiers** [comment]
Can we expect this to be working again now? Thanks!

**Comment by vjeux** [comment]
It got enabled back by github!

**Comment by aspiers** [comment]
Thanks - in the mean time it served as a good excuse to deploy my own bot, the logs from which are helping me understand how to configure it properly :)
