### ISSUE TITLE
Is GITHUB_USER and GITHUB_PASSWORD required for GHE?

### ISSUE THREAD

**Issue by defunctzombie** [facebook/mention-bot#136]
I don't understand why these two environment vars are required when the GITHUB_TOKEN var is present and can be used to provide the access needed. I am trying to get mention bot working on GHE and want to make sure that I configure it properly. I have made the expected config file changes but this last part with the env vars is confusing. Which parts apply to GHE vs the public instance.

**Comment by vjeux** [comment]
Unfortunately, there is no github api to fetch the blame information, so we are using the normal user login flow and parsing out the html.

If you know of a better way, please let me know!

**Comment by aspiers** [comment]
Why not just clone the git repo and then run `git blame` on it? Sounds a lot nicer than parsing HTML responses from github.

**Comment by aspiers** [comment]
Oh, you already considered that - I just saw https://github.com/facebook/mention-bot/blob/master/mention-bot.js#L152
