### ISSUE TITLE
support for multiple assignees

### ISSUE THREAD

**Issue by aspiers** [facebook/mention-bot#139]
Firstly, mention-bot is awesome!!  It's almost exactly what I was about to build, so I'm delighted to have found it - thanks a lot for sharing :)

GitHub recently added support for simultaneously assigning up to 10 people to a pull request:

- https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests

It would be great if mention-bot supported this too.  Of course it raises the question who should be assigned, and who should merely be mentioned.  There is no general answer to this, so it would need to be configurable.

In our team, we use assignment to indicate that a review is *required* by the assignee, whereas mentions would be considered as an invitation to *optionally* review.  I'm sure other teams would take different approaches.  So some thought is required in order to support the various possible use cases.  For example, we might want `alwaysAssignForPaths`, `fallbackAssignForPaths`, which can be set independently of their notify counterparts.  We probably wouldn't ever want to assign people based on the blame analysis, but maybe other users would.

Thoughts?  Thanks again!

**Comment by vjeux** [comment]
My usual line of thoughts for this is to implement whatever is needed for your project and avoid theorizing on what others could maybe want in the future. When that comes up, then try to adapt their use cases ;)

If you send a pull request to add support for whatever you need, I'll gladly accept it

**Comment by aspiers** [comment]
Yes I think you're absolutely right :)  I was thinking about this more, and couldn't come to any conclusion other than what you've just suggested.  I have a meeting with my team next week so hopefully we should soon figure out exactly what we need and will be able to send a PR which might work for other people too.  Thanks!

**Comment by vjeux** [comment]
Perfect!
