### ISSUE TITLE
glob syntax is undocumented

### ISSUE THREAD

**Issue by aspiers** [facebook/mention-bot#140]
The glob syntax supported for `alwaysNotifyForPaths` etc. is not documented, and since it's a somewhat extended glob dialect, this is definitely worth fixing.  I found by looking at the source that it uses [`minimatch`](https://github.com/isaacs/minimatch), so presumably we can just link to their documentation rather than needlessly duplicating what they have.

**Comment by vjeux** [comment]
Good call, if you send a pull request to update the doc i'll merge it in :)

**Comment by aspiers** [comment]
There you go :)
