### ISSUE TITLE
Getting double-notifications

### ISSUE THREAD

**Issue by djmitche** [facebook/mention-bot#149]
Recently the buildbot/buildbot project has started getting double mention-bot notices on our PR's, for example https://github.com/buildbot/buildbot/pull/2297.

I only see one webhook in the settings for the repository, though.

Any idea what's wrong?

**Comment by vjeux** [comment]
This is weird, thanks for the report, I'll investigate.

**Comment by vjeux** [comment]
I checked and we receive two http requests about each pull request. So it's something on the github side. Could you remove the webhook, try a pull request and maybe re-add it if it doesn't fix it. (The old reboot the computer technique and prays it works)

I looked at the logs and you are the only project I could see that behaves like this fyi.

**Comment by djmitche** [comment]
Oh, ugh, there's an org hook and a repo hook.  Sorry about that!

**Comment by vjeux** [comment]
Cool, glad you figured it out :)
