### ISSUE TITLE
Handle case where no reviewers found better

### ISSUE THREAD

**Issue by mwarkentin** [facebook/mention-bot#15]
Just got the following comment on a PR on one of my repos: 

> By analyzing the blame information on this pull request, we identified @none to be a potential reviewer.

Two options:

* Improve messaging: `We were unable to identify any potential reviewers. Sorry!`
* Don't make a comment at all if no reviewers were found

**Comment by vjeux** [comment]
Option #2 is currently implemented. However there's a bug where for some reason @none is being filled there somehow. A fix for this would be to just remove 'none' from the list at the end.

**Comment by mwarkentin** [comment]
Looks like this is where it would need to be changed: https://github.com/facebook/mention-bot/blob/d6b84f924acf254ac885e4bae4fac2059ce03a01/mention-bot.js#L261-L281

**Comment by vjeux** [comment]
Fixed: https://github.com/facebook/mention-bot/commit/50638bdcb6413b297f2bd292bb9d5ebc752261f4
