### ISSUE TITLE
Don't suggest the PR author as the reviewer

### ISSUE THREAD

**Issue by rhyolight** [facebook/mention-bot#16]
I've already seen this happen a few times, where the only person to blame is the author of the PR. In this case, it would be better not to comment.

**Comment by vjeux** [comment]
Good catch! Would be pretty simple to implement if you have some time: when the list is done, remove the author before slicing the first three :) Pull request welcome.

**Comment by rhyolight** [comment]
Ok, I'll take a look. Can you assign to me?

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by vjeux** [comment]
Sorry, github won't let me because you're not part of the facebook organization :(

**Comment by vjeux** [comment]
https://github.com/facebook/mention-bot/pull/19 fixed it!
