### ISSUE TITLE
The bot doesn't parse .mention-bot from the repo

### ISSUE THREAD

**Issue by tbassetto** [facebook/mention-bot#161]
Hi @vjeux, sorry I hadn't time to create the PR for https://github.com/facebook/mention-bot/issues/160 yet, and I haven't investigate this bug as much as I wanted either. I am leaving for vacation in 2 hours 😄 

I have added a `.mention-bot` file at the root of our repo getting PRs, and saw that the bot was not using it. I checked the logs, and surely the lines "Continuing with default configuration." had disappeared. The bot was finding the file, but not applying its configuration.

It turns out that `getRepoConfig` is getting an object with `data` and `meta` properties, and data is a `string`. Something like:
```js
// result =
{ data: '{\n  "maxReviewers": 2,\n  "numFilesToCheck": 10,\n  "message": "Hi @pullRequester! By analyzing the annotation information on this pull request, I identified @reviewers to be potential reviewers",\n  "alwaysNotifyForPaths": [{\n    "name": "tbassetto",\n    "files": ["blah/**/*.js"]\n  }, {\n    "name": "john12",\n    "files": ["blih/**/*.js"]\n  }, {\n    "name": "rick14",\n    "files": ["bleh/**/*.js"]\n  }],\n  "fileBlacklist": ["derp/*.json"],\n  "userBlacklist": ["cookiemonster"],\n  "assignToReviewer": true\n}\n',
  meta:
   { 'x-oauth-scopes': 'repo',
     'last-modified': 'Wed, 10 Aug 2016 09:22:55 GMT',
     etag: '"f6ea25b1784f40f5c53461fc040ddc85"',
     status: '200 OK' } }
```

I thus applied the following changes to make it work:
```diff
@@ -99,7 +100,12 @@ function getRepoConfig(request) {
       if (err) {
         reject(err);
       }
-      resolve(result);
+      try {
+        var data = JSON.parse(result.data);
+        resolve(data);
+      } catch (e) {
+        reject(e);
+      }
     });
   });
 }
```

I am wondering how it works for so many people but no us 🤔

We are using GitHub Enterprise 2.6, with the API V3. `mention-bot` is ran with `node 4.4.7` (LTS).

**Comment by vjeux** [comment]
Maybe it actually never worked...

**Comment by vjeux** [comment]
Enjoy your vacation! Feel free to send this patch when you come back :)
