### ISSUE TITLE
Empty value for parameter 'user': undefined

### ISSUE THREAD

**Issue by davido-bs** [facebook/mention-bot#167]
Running mention-bot as a Docker container for a private repo:
```
sudo docker run -e GITHUB_USER="<github_user>" -e GITHUB_PASSWORD="<password>" -e GITHUB_TOKEN="<a_personal_access_token>" -p 5000:5000 mention-bot
```
The Personal Access Token being used has everything (and only everything) under the "Repo" category:
``Repo`` Full control of private repositories
``repo:status`` Access commit status
``repo_deployment`` Access deployment status
``public_repo`` Access public repositories
Received this message after setting up the Webhook and opening a pull request:
```
[TypeError: Cannot read property 'html_url' of undefined]
{ [Error: Empty value for parameter 'user': undefined]
  defaultMessage: 'Bad Request',
  message: 'Empty value for parameter \'user\': undefined',
  code: '400',
  status: 'Bad Request',
  headers: undefined }
Skipping because action is undefined. We only care about: "opened"
```

**Comment by davido-bs** [comment]
Misconfigured on our side; we figured it out.

**Comment by caarlos0** [comment]
What was the problem @davido-bs ?
