### ISSUE TITLE
"annotation information" is slightly confusing

### ISSUE THREAD

**Issue by waldyrious** [facebook/mention-bot#171]
Normally an annotation is considered to be something done manually, so I was a bit confused when I saw the default message saying that the bot analyzed "the annotation information on this pull request".

I agree with the change away from "blame" in #142, and the motivation to defer to git terminology, but I'd offer that the annotations on `git annotate` are actually generated on-the-fly when the command is called, out of metadata present in the repo, rather than annotations that are themselves part of the commits (and even less so the PR, since the important thing is the history of the files *prior* to the PR, not the info in the commits of the PR itself).

How about `By analyzing the history of the files in this PR`? /cc @ZauberNerd @vjeux

**Comment by vjeux** [comment]
@waldyrious thanks for the suggestion, I'm down for it. Can you send a pull request to update it? Thanks!

**Comment by waldyrious** [comment]
Sure, that was my intention. I'll just wait a bit to see what @ZauberNerd's thinks :)

**Comment by ZauberNerd** [comment]
@walyrious sure go ahead. That does indeed sound nicer than annotation information ;)

**Comment by waldyrious** [comment]
Glad you guys agree. I'll submit the PR then.
