### ISSUE TITLE
Mention Bot offline and user missing?

### ISSUE THREAD

**Issue by robbiet480** [facebook/mention-bot#176]
Just added @Mention-Bot to @home-assistant a couple of days ago. I noticed this morning that @mention-bot hasn't been around the last few days and it's user account is now 404ing. What happened?

**Comment by vjeux** [comment]
Grrr, github must have banned the bot again :(

**Comment by vjeux** [comment]
Just sent a support request. In the past it took ~24h for them to reinstate the bot

**Comment by robbiet480** [comment]
@vjeux Reached out to some Github friends to see if we can move this along any faster. It's Hacktoberfest, so we have a lot of PRs coming in that need review! :)

**Comment by robbiet480** [comment]
Bot is back

**Comment by robbiet480** [comment]
@vjeux I am now seeing @mention-bot making comments on PRs again. Closing this.

**Comment by vjeux** [comment]
Yay, thank you!
