### ISSUE TITLE
Allow the mention bot to hook into review requests in addition to of assignees

### ISSUE THREAD

**Issue by connor4312** [facebook/mention-bot#192]
New feature, would be nice to have in the mention bot! https://github.com/blog/2291-introducing-review-requests

**Comment by vjeux** [comment]
Sounds awesome indeed! I won't have the time to work on it anytime soon but would love to see it happening.

**Comment by caarlos0** [comment]
I think there is no API for that yet :/

https://developer.github.com/v3/pulls/

**Comment by vjeux** [comment]
Mention-bot is already logged with a user token so we can send normal http requests like a user would if you want ;)

**Comment by jimmidyson** [comment]
API is available now - submitted #198 which adds option to create review requests.
