### ISSUE TITLE
Feature: Automatically create Review Requests

### ISSUE THREAD

**Issue by josepjaume** [facebook/mention-bot#195]
Github [recently introduced a Review Request](https://github.com/blog/2291-introducing-review-requests) feature that fits like a glove into mention-bot.

AFAIK there's no API yet, but GitHub will probably launch it sometime soon.

**Comment by vjeux** [comment]
That would be awesome indeed. I won't likely implement it myself but would welcome a pull request for it

**Comment by jimmidyson** [comment]
Submitted #198 for this - would be really useful.
