### ISSUE TITLE
Don't mention the PR creator as a potential reviewer

### ISSUE THREAD

**Issue by cachedout** [facebook/mention-bot#218]
IMHO, mention-bot should automatically exclude the submitter of a PR from the list of potential reviewers or at least allow an option to do so.

**Comment by mspangdal** [comment]
https://github.com/facebook/mention-bot/blob/master/mention-bot.js#L608
theres code that should exclude the creator,  unless explicitly set as a fallback reviewer for the code path or similar case

**Comment by cachedout** [comment]
@mspangdal Interesting. I heard about this one second-hand so I'll see if it happens again and if so, I'll re-open this issue with more details. Thanks.
