### ISSUE TITLE
No comment in my PR

### ISSUE THREAD

**Issue by imcaffrey** [facebook/mention-bot#23]
I ran this mention-bot on heroku, and I set up the webhooks as required.

I can see from the log that my bot received the webhook and checked the blame.

But I don't get a comment in my PR.

I wonder what might be causing this problem? Thanks.

**Comment by vjeux** [comment]
What is the pull request? i can take a look and see what's going on

**Comment by imcaffrey** [comment]
@vjeux Thanks! The link is here: https://github.com/24OI/Standard_Code_Library/pull/22

I didn't paste my log here because I didn't understand which part contained my persona info.

**Comment by vjeux** [comment]
So, you added a file here. Because there was no pre-existing code, there is no one we can look for in the blame.

I made the explicit decision of the bot being silent when this happens because we don't want to send an email with absolutely no useful information.

Try sending a pull request that edits a file instead (which you are not the sole committer on)

**Comment by imcaffrey** [comment]
@vjeux Thanks for your help.

From the log I noticed that my bot got the blame from here: https://github.com/24OI/Standard_Code_Library/blame/master/c++/String/README.md

You can see that the original author didn't have a valid email.

I think the problem results in here.

**Comment by imcaffrey** [comment]
The diff is here : https://patch-diff.githubusercontent.com/raw/24OI/Standard_Code_Library/pull/11.diff

Here is a part of the log file. It's crazy that I didn't get info from the bot. What might be wrong then?

```
2015-11-23T05:07:59.429298+00:00 heroku[router]: at=info method=POST path="/" host=mention-bot-24oi.herokuapp.com request_id=75c5372e-ab55-4aa8-a324-a9c7d56a4331 fwd="192.30.252.41" dyno=web.1 connect=1ms service=4ms status=200 bytes=117
2015-11-23T05:09:15.081129+00:00 heroku[router]: at=info method=POST path="/" host=mention-bot-24oi.herokuapp.com request_id=a0972140-59b2-43d5-a745-fdca654dfbfa fwd="192.30.252.34" dyno=web.1 connect=1ms service=12ms status=200 bytes=117
2015-11-23T05:12:00.805274+00:00 heroku[router]: at=info method=POST path="/" host=mention-bot-24oi.herokuapp.com request_id=a142cf8d-929a-4dc1-87ae-b5c396b0e6b8 fwd="192.30.252.41" dyno=web.1 connect=1ms service=3ms status=200 bytes=117

```

**Comment by vjeux** [comment]
Can you put console.log everywhere and see where it stops working? :)

**Comment by imcaffrey** [comment]
@vjeux Thanks. It seems that heroku doesn't allow an ssh connection to my app? So the only way out is to push with git? I'll be checking this.

**Comment by imcaffrey** [comment]
@vjeux I've found out the problem. 

In my log it showed that the 'data.action' was not 'opened', but 'synchronize' instead

https://github.com/facebook/mention-bot/blob/master/server.js#L70-L72

So I commented the lines and it is working now: https://github.com/24OI/Standard_Code_Library/pull/11#issuecomment-158864788

https://github.com/imcaffrey/mention-bot-24oi/commit/0aabe7345adb22fb059c53ca0df2e87fbafed499

Thanks for your help.

**Comment by imcaffrey** [comment]
My fault here. I didn't open a PR. I just used an old PR, so it's action was not 'opened'.

Sorry for bothering. I now understand how it works.

**Comment by imcaffrey** [comment]
Perhaps there should be an option... people like me hope that the lines to be like this:

```
    if (data.action === 'closed') {
      console.log('Pull Request Closed!');
      return res.end();
    }
```

**Comment by vjeux** [comment]
I don't really want to add more logging than necessary here. If people have trouble setting it up they can add console.log themselves.

One thing we could add as logging is for every place where we stop, say why.

if (data.action !== 'opened') {
  console.log('Action is ', data.action, ' and not "opened", skipping);
}

**Comment by imcaffrey** [comment]
@vjeux I agree with you. It might be better to add log messages before the res.end() part.

**Comment by vjeux** [comment]
Send a pull request my way :)

**Comment by imcaffrey** [comment]
@vjeux Did you mean things like this? https://github.com/imcaffrey/mention-bot/commit/884bf49812f78f5d8bba97d74e9a4106508f67f2

**Comment by vjeux** [comment]
Exact
