### ISSUE TITLE
Add global configuration variable with a default of 3 on number of people to be added for review

### ISSUE THREAD

**Issue by udnisap** [facebook/mention-bot#24]
It is currently hardcoded at https://github.com/facebook/mention-bot/blob/master/mention-bot.js#L300
Is this a desirable feature?

**Comment by vjeux** [comment]
Sure, if you implement it, I'll take it :)

**Comment by jgardella** [comment]
I have this implemented on my fork, I'll submit a PR later today.

**Comment by udnisap** [comment]
I can help if you need

**Comment by vjeux** [comment]
I'm closing this since I'm not going to work on it, but feel free to send a pull request if you get it working :)
