### ISSUE TITLE
mention bot generator with a cli interface

### ISSUE THREAD

**Issue by udnisap** [facebook/mention-bot#29]
Based on the current implementation based on the my understanding, user needs to checkout the project add the configuration on the project it self and then deploy to a server. 
How about a `yo` generator that asks these configurations and setup a project that can be deployed to a server. This can be distributed via `npm` as a generator and people can use this like

```
npm install generator-mention-bot // or npm install mention-bot-cli
yo mention-bot
Name of the bot: My Awsm Bot
What is the repo url: some git url
.. Any other configuration 
Enter your heroku details:   
.... 
npm push  // to push heroku with toolbelt
```

**Comment by imcaffrey** [comment]
:+1:

**Comment by udnisap** [comment]
@vjeux any suggestions, ideas. I can work on this if this is a desirable feature.

**Comment by zekenie** [comment]
I'm not sure this is needed because the only configuration needed is
environment variables. I think Yo is a good tool for pre-configiruing code.
Perhaps it could be nice to write the new config file but it feels like
using a chainsaw to cut bread.

**Comment by udnisap** [comment]
I like the analogy. :point_up:

**Comment by vjeux** [comment]
Is there a real need for this? It seems to me like a lot of heavyweight work that's not going to be very useful. Closing for now, but feel free to comment if you really want something like this.
