### ISSUE TITLE
Heroku button

### ISSUE THREAD

**Issue by mwarkentin** [facebook/mention-bot#4]
It'd be awesome to have a [Heroku Button](https://devcenter.heroku.com/articles/heroku-button) to launch this easily on Heroku.

**Comment by vjeux** [comment]
Can you explain what's the use case? I'm not really sure I understand

**Comment by mwarkentin** [comment]
It gives you a button right in the Github readme that would let anyone easily launch their own mention-bot instance on Heroku.

Here's an example for launching a Hubot: https://github.com/hipchat/triatomic

There are many other examples here: https://elements.heroku.com/buttons

**Comment by mwarkentin** [comment]
If I have some time I could take a swing at it later (probably on the weekend).

**Comment by vjeux** [comment]
Nice. If you send a pull request that sets it up, I'll gladly accept it :)

**Comment by mwarkentin** [comment]
Sounds good!

**Comment by vjeux** [comment]
It's live!

**Comment by mwarkentin** [comment]
@vjeux Hah.. I decided to go ahead and do it myself, guess I was a bit too slow. :)

Maybe see if any of the extra stuff I provided in `app.json` is valuable and merge them in?

**Comment by vjeux** [comment]
Sure, can you update your pull request to rebase and add this additional info?
