### ISSUE TITLE
Github auth cookies does not work with GH:E

### ISSUE THREAD

**Issue by Friss** [facebook/mention-bot#47]
In it's current form it always uses github.com and wouldn't try to auth with a GH:E instance.

**Comment by vjeux** [comment]
Do you want to submit a pull request to fix it?

**Comment by Friss** [comment]
Yeah I just didn't have a chance to pull out that one change as I was working on it. Figured I'd document the bug

**Comment by vjeux** [comment]
Thanks :) Can't wait to see it!
