### ISSUE TITLE
Org members?

### ISSUE THREAD

**Issue by perplexes** [facebook/mention-bot#5]
Does this limit the "owners" of code to org members? We have a lot of code that was written by people who no longer work here.

**Comment by vjeux** [comment]
It does not. It pings whoever has the blame. I was actually pretty surprised on react-native as it pinged a lot of people not working at Facebook.

Do you have a suggestion on how to fix that?

**Comment by mwarkentin** [comment]
You could take in an list of "valid organizations" as an environment variable, ping the [org api](https://developer.github.com/v3/orgs/members/) and filter based on that.

Feels like the use cases might be different depending on if the project is private or public - not sure what happens if you mention someone who doesn't have access on a private project. Maybe for private repos, it could hit the org api and filter on members automatically.

**Comment by perplexes** [comment]
It'd also be nice to filter out specific people. For a long time at our company there was just one/two people so they have their names on everything. Now we're at 8 engineers, so it'd be more appropriate to ping the next-best candidate.

**Comment by vjeux** [comment]
Right now the bot doesn't work on private repos because it hits the website and is not authenticated by the way.

**Comment by GrayHatter** [comment]
How hard would it be to implement a whitelist or blacklist?

**Comment by GrayHatter** [comment]
Or check the blame, and only tag them if the last "blame commit" was x days/weeks/months ago

**Comment by vjeux** [comment]
Would be pretty easy. Pull requests are welcome :)

Also, one great thing is that you can run it on existing pull requests and just output the list of names. This way you can iterate over the algorithm to get what you are hoping for.

**Comment by jgardella** [comment]
I've started implementing user blacklisting and requiring of organization membership on my fork. I haven't worked with the GitHub API before so any help is appreciated!

I'd be interested to hear from @vjeux if you have any ideas about how to allow repos to have their own configuration settings that the bot can parse? Or if that's even a direction you would want to take this.

**Comment by vjeux** [comment]
We're using a completely different implementation at Facebook so this is pretty much only for the community. If you want to add configurations, I'm all for it :)

**Comment by jgardella** [comment]
How are repo-specific configurations usually done for these bots? A config file in the repo source that the bot parses?

**Comment by mwarkentin** [comment]
@jgardella That seems like the most straightforward way to me - also similar to how you'd configure Travis, CircleCI, etc.

Add a `.mentionbot` file in the root (yaml, json, or ini-style?) which the bot could check before running when a PR is created.

**Comment by jgardella** [comment]
So, my PR  that just got merged adds support for a config file `.mention-bot`, and a config property for blacklisting users, so they never get mentioned.

The other option brought up in this issue, setting required organizations, is a bit more complicated. The wrapper we're using for the GitHub API makes async calls, but the way the bot is currently structured, it does everything synchronously (downloading the blame, downloading the diff, etc). To my mind, we can either rewrite the bot to work entirely async, or write our own sync function that retrieves a user's organizations from the API. Interested to hear others' thoughts.

**Comment by zekenie** [comment]
It seems like a great idea to make it async especially because its an http
server. It also seems like it needs to be all sync or all async. It seems
like a solid chunk of work, but I'd be happy to take a stab over
thanksgiving

**Comment by vjeux** [comment]
If you are going the async route, please use async/await with babel. This makes the code look like it is synchronous

**Comment by zekenie** [comment]
Never done that before but doesn't that require something like Koa instead of express?

**Comment by vjeux** [comment]
Express requires you to manually call res.end(); So you can write the code as

```javascript
async function doWork() {
  var org = await queryOrg();
  // ...
}

req.pipe(bl(function(err, body) {
  doWork().then(function() { res.end(); })
}));
```

**Comment by zekenie** [comment]
would it be better to just use promises heavily?

**Comment by vjeux** [comment]
Async await is using promises under the hood. It's just a 100x better way to write async code. Just try it and I promise you won't want to go back to raw promises ;)

**Comment by zekenie** [comment]
The express server isn't doing too much... I'm kind of into trying koa... would you be open to that?

**Comment by vjeux** [comment]
Sure, have fun with it.

**Comment by vjeux** [comment]
https://github.com/facebook/mention-bot/commit/3bfcc0a6187e1788d154ce809b20acbf77aa5351 added a blacklist. Closing this issue. If you want more configuration, please open up another issue :)

**Comment by jgardella** [comment]
@zekenie Have you put any work into the async? I'd like to give it a shot if not.
