### ISSUE TITLE
Timing out when using the Deploy to Heroku button

### ISSUE THREAD

**Issue by itsmeduncan** [facebook/mention-bot#61]
I just setup `mention-bot` on Heroku using the "Deploy to Heroku" button. All the webhooks are firing, but Heroku is timing out in about 30 seconds whenever I send a payload. I've tried this manually using cURL as well as the retry webhook function on GitHub. Any thoughts on why this might be happening? I bumped the server to a non-free one and it was still happening.

**Comment by bbenoist** [comment]
@itsmeduncan I am suffering from similar timeout issues. Did you found a solution? :cry:

**Comment by bbenoist** [comment]
#62 helped me remarking that the timeout was due to missing .mention-bot file.
After adding an empty one (i.e. `{}`), it seems to be OK...
