### ISSUE TITLE
Add error message when the github login fails

### ISSUE THREAD

**Issue by bbenoist** [facebook/mention-bot#64]
Hi, 

I am still having issues making an Heroky instance of mention-bot work with my private repos.

Webhook seems to be transmitted successfully but mention-bot keeps printing "Skipping because there are no reviewers found" even when I modify files where there should be reviewers.

Here is the only log I have (actual URLs, IDs and IPs has been faked for privacy reasons):

> 2015-12-16T16:50:40.702001+00:00 heroku[router]: at=info method=POST path="/" host=my-mention-bot.herokuapp.com request_id=ae90ffe6-d885-4e67-a9a5-f1365456c004 fwd="192.30.232.41" dyno=web.1 connect=1ms service=1008ms status=200 bytes=117
> 2015-12-16T16:50:40.690816+00:00 app[web.1]: https://github.com/my/project/pull/10 []
> 2015-12-16T16:50:40.690866+00:00 app[web.1]: Skipping because there are no reviewers found.

I am not yet accustomed with both NodeJS and Heroku :baby:. Appart from reading those log lines, what is the simplest way for me to debug my problem?

**Comment by vjeux** [comment]
This is the line that's doing this console.log:
https://github.com/facebook/mention-bot/blob/master/server.js#L152-L155

There are two ways to debug this:

1) Easy but slow way: you add console.logs everywhere, do a `git commit`/`git push heroku master`, recreate a pull request and using `heroku logs --tail` see what's going on and repeat.

2) A bit more annoying but faster way: In https://github.com/facebook/mention-bot/blob/master/server.js#L100 add a console.log(body) and push to heroku. Create the pull request and look at the logs. Create a file on your local machine with the content of the body in a file called `body.webhook`. Then run the server locally with `GITHUB_TOKEN=insert_token_here npm start` and do 

```
curl -X POST -d @body.webhook http://localhost:5000/
```

Every time you need to change the debug code, just kill / re-run the server and re-run the curl.

**Comment by bbenoist** [comment]
Thank you for this good and pragmatic help!

It seems that my problem comes from the GitHub authentication. This is the content of the `.diff` patch request:
```
    {"error":"Not Found"}
```

**Comment by bbenoist** [comment]
OMG :scream: I found out what the problem was!

The password I choosed for my bot GH account contained a `$` sign which was interpreted as an environment variable during the authentication :cry:

**Comment by vjeux** [comment]
Oh noes :(

Would be nice to add proper error logging when the authentication fails. So that it shows up in the logs. Want to send a pull request?

**Comment by bbenoist** [comment]
> Would be nice to add proper error logging when the authentication fails. So that it shows up in the logs.

:+1: This would have made my debugging easier.

> Want to send a pull request?

No that I don't want but as I am currently submerged by tasks, I would prefer it to be either assigned to someone else or left opened until someone (might still be myself) has enough time to take care of it.

Anyway, thank you again for your help and for your work on mention-bot. Everything seems to be working fine now :smiley:

**Comment by vjeux** [comment]
Perfect! If you are bored during the weekend, you know what to do ;)

**Comment by bbenoist** [comment]
@udnisap :+1:
