### ISSUE TITLE
Exclude requires.io bot from mentiong on heroku instance

### ISSUE THREAD

**Issue by ad-m** [facebook/mention-bot#67]
Hello,

I suggest exclude  @requires from mentioning in default settings and on ```https://mention-bot.herokuapp.com/``` instance.

@requires is github bot too. It submit pull requests with updated dependencies (see fg. https://github.com/watchdogpolska/poradnia/pull/196 ). It is useless to mention bot about update of packages which it upgraded last time. mention-bot should notify person who added requirements in this cases and skip @requires.

Greetings,

**Comment by jgardella** [comment]
This isn't a serverside setting, but is instead one of the repo-specific settings that can be set in your repo's `.mention-bot` file. Add @requires and any other bots to the `userBlacklist` in your config file, and they will never be mentioned. See [the example config](https://github.com/facebook/mention-bot/blob/master/CONFIG.md) for this and other settings you can define on a repo-by-repo basis.

**Comment by ad-m** [comment]
Thanks for you reply. Unfortunately, I think that the repo-level settings are not the best solution in all cases. I using org-level integration (see #41). If I have create repo-level settings to exclude @requires I lost benefits of org-level integration. 

I can see two solutions:

 1. provide default ```userBlacklist``` server-side (for public bots only, sign-in by issues here, documented instance),
 2. provide settings by payload URL (I'm not sure).

What do you think?

Greetings,
