### ISSUE TITLE
503 when getting blame information

### ISSUE THREAD

**Issue by jemise111** [facebook/mention-bot#68]
I'm trying to set up mention-bot on a private repo. I have a fork deployed to Heroku (so I could add some extra logging). Parsing the diff seems to be working just fine but it looks like I'm getting a request timeout when trying to get blame information. E.g. https://github.com/<repo>/blame/<branch>/<path_to_file>.

Any ideas why that might be happening?

(awesome project btw, I really hope I can get it working!)

**Comment by vjeux** [comment]
I have no idea I'm sorry :( Can you try to add console.logs and figure out where it breaks? Please re-open if you have more information.
