### ISSUE TITLE
Declare mandatory reviewers for files matching specific wildcards

### ISSUE THREAD

**Issue by bbenoist** [facebook/mention-bot#70]
It would be nice to have the option to declare mandatory reviewers for specific files.

Some use-cases:

* Language-experts:

  ```json
  "*.c,*.cpp" : "jdoe"
  "*.py" : [ "fbar", "jbegood" ]
  ```

* Banned files:
  ```json
  "*.bin:" : "glfs"
  ```

* Specific directory:

  ```json
  "help/**" : "wshakespeare"
  ```

* Translators

  ```json
  "i18n/*fr*" : "mcapello"
  "i18n/*ru*" : "ltolstoi"
  ```

**Comment by vjeux** [comment]
Check out the `alwaysNotifyForPaths` option in `.mention-bot` file

https://github.com/facebook/mention-bot#configuration

**Comment by bbenoist** [comment]
Thanks for info and sorry for not having RTFM.
