### ISSUE TITLE
need for an account without 2FA?

### ISSUE THREAD

**Issue by miketheman** [facebook/mention-bot#76]
Hi gang,

We've really liked the ideas that you're putting together here, and wanted to try launching this for our org

Unfortunately, as part of our policy, any user with read access to our github repos _must_ have two-factor auth enabled, and I can see that from #64 and #75, this is currently not set up to work this way.

We were curious to know if anyone is working towards a nodegit token based clone solution as mentioned in #8, since that would help remove the need for a user/pass, cookies, etc ?

**Comment by caarlos0** [comment]
Hi @mikematas , I just started something like that, the only remaining problem is the blame download...

https://github.com/facebook/mention-bot/compare/master...caarlos0:cookie?expand=1

**Comment by miketheman** [comment]
Poor Mike Matas, got pinged for unrelated. :grin: 

@caarlos0 That indeed looks interesting - I found a python-based API method that might be interesting to read to get inspiration on how that might be done: https://github.com/hulu/restfulgit/pull/70/files

**Comment by caarlos0** [comment]
ooops, sorry @mikematas :(

**Comment by caarlos0** [comment]
@miketheman will take a look at home...

**Comment by arrrnas** [comment]
any update on this?

**Comment by zoidbergwill** [comment]
Hi @caarlos0 

Shouldn't https://github.com/facebook/mention-bot/compare/master...caarlos0:cookie?expand=1#diff-075b835dda5f5878dfe639e1b26406c6R442 be `${targetBranch}`?

**Comment by caarlos0** [comment]
@zoidbergwill yeah, I need to continue working on that actually..

**Comment by vjeux** [comment]
I'm going to close this one down until progress is made. Please feel free to open a new one in the future :)
