### ISSUE TITLE
Private repos

### ISSUE THREAD

**Issue by alanctkc** [facebook/mention-bot#8]
I'm attempting to do a little rewriting of the diff/blame download to respect `GITHUB_TOKEN` and open mention-bot up to be used on private repos.

I was thinking something roughly along these lines (WIP): https://github.com/facebook/mention-bot/compare/master...alanctkc:private-repos

Seems, however, since the bot is just hitting the HTML blame route and doing parsing there (and I can't find any trace of an official GitHub blame API) might be out of luck. Any clever ideas on how to auth with the HTML route?

Will probably just abandon if not, but we'd love to use mention-bot on internal projects. :)

**Comment by vjeux** [comment]
Yeah, I originally wanted to develop it on a private repo but sadly there's no apis for blame and diff. The way I used to workaround that on previous projects is to actually go through the normal website auth flow and maintain cookies across requests. (If you are curious, see this PHP project I wrote that does that: https://github.com/vjeux/phpFileDownload )

If you feel like implementing this, shouldn't take more than a few hours and be really useful :)

**Comment by alanctkc** [comment]
Man, that sounds crazy. I'm not beyond hacks like that, though if it can work for such a common use case. :rocket: 

My only qualm.. does that lean on the actual GH account password? I wish I could keep it token-based still to not get weird with passwords. The diff part can be retrieved using the API+token with the right `Accept` header: https://github.com/alanctkc/mention-bot/blob/0af264e9ea382a5473ff0357c0895390eeffb493/mention-bot.js#L296 Just no blame.

I may fall back to the password thing and give that a whirl for kicks.

**Comment by vjeux** [comment]
Another way to get the blame would be to `git clone` the repo, do `git blame` and then do an http request to get the github username (instead of the git email). This would avoid storing the password but be super slow and wasteful.

**Comment by skyhighwings** [comment]
It'd be "super slow and wasteful" for a public service, but for an internal CR bot it'd be totally acceptable, especially if it cached the repo + usernames.

**Comment by vjeux** [comment]
@skyhighwings good point :) Want to give it a try?

**Comment by skyhighwings** [comment]
I can give it a look but I'm really busy right now as a result of working on moving across the USA. I'll have more time to check it out in a month :disappointed:

I don't mean to diminish the work on this — it's super awesome! I'll probably end up using it on personal projects.

**Comment by skyhighwings** [comment]
@vjeux I can give it a look but I'm really busy right now as a result of working on moving across the USA. I'll have more time to check it out in a month :disappointed:

I don't mean to diminish the work on this — it's super awesome! I'll probably end up using it on personal projects.

**Comment by skyhighwings** [comment]
Some resources I've got from poking through the code:

So currently, as I see it, we get the diff via the following:
https://github.com/facebook/mention-bot/blob/master/mention-bot.js#L287

To facilitate this, there needs to be some easy way to get the diff of a specified PR. With https://developer.github.com/v3/pulls/ we're able to get the data requisite to fetch the given remote (`.head.repo.git_url` and `.base.repo.git_url`), along with the ref to diff against (`.head.ref` and `.base.ref`). From there it's just `git diff (base-ref) (head-ref)` to get the new diff. The tricky bit is getting the repo contributor names from their emails which will require some non-default params to `git blame` — I recommend `git blame --line-porcelain` if you want to get fancy, or `git diff -e` to show the email. The stumbling block is here — I don't see any way to get the Github username of an arbitrary email or human name via https://developer.github.com/v3/repos/collaborators/ , so the Github `/blame/` endpoint is the best we have right now. :crying_cat_face:

**Comment by vjeux** [comment]
@skyhighwings the blame info gives you the author as an email but -also the commit- which was responsible. You can query github API for the commit and get the github username from it :)

**Comment by skyhighwings** [comment]
@vjeux oh, thanks! that's valuable information. I'll keep poking at this when I have spare time.

**Comment by zekenie** [comment]
It would be so awesome to have this for private repos!

**Comment by zackify** [comment]
Any plans for gitlab support? I figured that goes along with private repos.

**Comment by vjeux** [comment]
@zackify none from me, but pull requests welcome

**Comment by alanct-minted** [comment]
So, the best option as I see it (and as @vjeux suggested) is to use the `GITHUB_TOKEN` to `git clone` over https: https://help.github.com/articles/git-automation-with-oauth-tokens/

Nodegit will probably be helpful here: http://www.nodegit.org/api/cred/#userpassPlaintextNew

Then, do a `git blame` on that repo and parse as usual from there. Obviously it would require git to be installed on web nodes, but I think at least for Heroku dynos, we have git in the slugs for free, right?

The PR diff is easy enough to still do through the API as shown in my original branch link above.

Not saying I have time to implement within the next week necessarily, but seems like the best shot for running on a private repo without requiring a separate auth mechanism (password/SSH key).

**Comment by zekenie** [comment]
Forgive me if this is a painfully obvious question or if we've already addressed this in the thread.

We need to:
- upon PR clone down master 
- reproduce [this](https://github.com/facebook/mention-bot/blob/master/mention-bot.js#L305) without hitting that blame url?
- implement a `parseBlame` for git/node-git's blame output

Is that correct? I might take a stab at this this weekend, but no promises ;)

**Comment by alanctkc** [comment]
@zekenie Bingo, I think that's exactly how I'd imagine it!

A couple smallish things to consider:

- It would be good to double-check whether or not the repo exists and do a pull instead of clone on the PR event if the repo exists (new deployment vs "cached" repo)
- To translate the `git blame` output back into mentionable GH usernames, you'll likely have to parse out the git commit shas for each blame line in your `parseBlame` (GH username isn't present), then hit the [GitHub API for that commit](https://developer.github.com/v3/repos/commits/#get-a-single-commit) to get the username ([@vjeux's suggestion](https://github.com/facebook/mention-bot/issues/8#issuecomment-158238669))

**Comment by alanctkc** [comment]
Actually, this may be a nice approach to make sure the local working tree is clean no matter what happened on the remote (instead of plain ol' pull): http://stackoverflow.com/a/8888015

**Comment by zekenie** [comment]
@alanctkc thanks!

**Comment by andrewpile** [comment]
FWIW, you can get private repo diffs through the API by using [custom media types](https://developer.github.com/v3/pulls/#custom-media-types), in this case `application/vnd.github.diff`

For example:

```
curl -H "Authorization: token <token>" -H "Accept: application/vnd.github.diff" https://github.com/repos/facebook/mention-bot/pulls/1
```
