### ISSUE TITLE
Add support for alternative ways of finding reviewers

### ISSUE THREAD

**Issue by jcsmorais** [facebook/mention-bot#80]
Hi guys,

I'm writing to ask you if there any future plans on adding support for alternative ways of finding reviewers, in my use-case I cannot rely on blame to find who should review certain changes since, for a various number of reasons, the person who touched that file recently might not be part of the team who is supposed to own it, with that in mind, having support for some sort of map between files/folders and people/teams would definitely help.

I would like to hear your thoughts around this matter and if this would be something that you guys would be welcoming to support.

Thanks

**Comment by vjeux** [comment]
No plans to implement anything of that sort but if you implement it and it makes sense, I see don't see a reason not to take it

**Comment by jcsmorais** [comment]
Hi @vjeux I attached a PR in order to add support for the aforementioned behaviour let me hear your thoughts.

Basically I'm introducing a new config file called `findPotentialReviewers` which defaults to `true` (maintaining the current behaviour) but also opens the possibility to use the `alwaysNotifyForPaths` for guessing purposes only instead.

Thanks
