### ISSUE TITLE
Add support for multiple PR actions listening

### ISSUE THREAD

**Issue by jcsmorais** [facebook/mention-bot#82]
Hi guys,

I noticed that by default mention-bot only listens to `opened` action, in my use-case I need him to be able to listen to other actions as well, other people might have similar requirements too, so my proposal is that we introduce a new config flag called `actions` which defaults to `opened` (maintaining the current behaviour) but also opening the possibility to listen to other actions such as `synchronize`.

Let me hear your thoughts.

Thanks

**Comment by jcsmorais** [comment]
Proposed changes: https://github.com/facebook/mention-bot/pull/83

**Comment by vjeux** [comment]
Why would you want to do it on synchronize? Do you want the bot to comment every time the person updates the pull request?

**Comment by jcsmorais** [comment]
@vjeux yes, please see my comment [here](https://github.com/facebook/mention-bot/pull/83#issuecomment-173969068).
