### ISSUE TITLE
Mention-bot stopped working?

### ISSUE THREAD

**Issue by tambry** [facebook/mention-bot#87]
Hi!

Recently mention-bot no longer seems to present on our repository.
The repository in question is [RPCS3/rpcs3](https://github.com/RPCS3/rpcs3)
Looking at the webhooks, the deliveries seem to succeed without any problems.
Any ideas what the issue could be?

Thanks in advance,
Raul

**Comment by tambry** [comment]
Mention-bot seems to have reappeared!

**Comment by tambry** [comment]
Mention-bot seems to have reappeared!

**Comment by vjeux** [comment]
Sorry about that, i'm using the free plan for mention bot on heroku and they turn it off a few hours a day. Maybe i'll pay it up but that's a bit annoying :x

**Comment by domenkozar** [comment]
Again?

**Comment by tambry** [comment]
Well, yes. He said it doesn't work for a few hours of the day.

**Comment by domenkozar** [comment]
What would the costs be

**Comment by domenkozar** [comment]
@vjeux I'd happily organize sponsoring a heroku dyno for a year. How do we do that and how much it costs?

**Comment by tambry** [comment]
Seems like Heroku Hobby is the first tier, that never sleeps and costs 7$/month, it would seem.

**Comment by vjeux** [comment]
I just upgraded to hobby which is indeed $7/month. Please let me know if it's still broken for time to time

**Comment by domenkozar** [comment]
Thanks!

**Comment by domenkozar** [comment]
@vjeux is it running? I see no comments from the bot at https://github.com/NixOS/nixpkgs/pulls

**Comment by vjeux** [comment]
Okay, so turns out that the bot got flagged by the bot detection script from github (how ironic). I contacted their support channel to get it back up.

"One of our mostly harmless robots seems to think you are not a human.
Because of that, it’s hidden your profile from the public. If you really are human, please contact support to have your profile reinstated. We promise we won’t require DNA proof of your humanity."

**Comment by vjeux** [comment]
Github unbanned the bot. Should be good to go now :) Let me know if it is not the case

**Comment by domenkozar** [comment]
:beers:
