### ISSUE TITLE
Add custom message

### ISSUE THREAD

**Issue by paked** [facebook/mention-bot#9]
I think it'd be pretty great if a custom message could be supplied for the bot to comment with on PRs.

**Comment by vjeux** [comment]
I'm curious, what message would you like instead? Maybe we can improve the default one.

**Comment by zekenie** [comment]
I thought it would be cool if the reviewer member names were github checkboxes

- [ ] like
- [ ] this

**Comment by paked** [comment]
@vjeux I think it just becomes a bit repetitive. Perhaps it could pick randomly from a list of possible options?

@zekenie what function would the checkbox serve though?

**Comment by zekenie** [comment]
Something like "I'll take it." I don't think it'd be a good universal message, but it would work well in my organization. Often it mentions too many people.

**Comment by phase** [comment]
I think it's a little verbose for just mentioning people that may want to review the PR. I think...
> By analyzing the blame information on this pull request, we identified @phase, @phase and @phase to be potential reviewers.

...could be changed to...

> I have identified that @phase, @phase and @phase are potential reviewers.

But a config variable would be the best option.

**Comment by paked** [comment]
:+1:

**Comment by udnisap** [comment]
@jgardella can this be added too?

**Comment by georgecodes** [comment]
I came up with [this](https://github.com/facebook/mention-bot/pull/31) if it helps.

**Comment by paked** [comment]
:+1:

**Comment by vjeux** [comment]
Fixed by https://github.com/facebook/mention-bot/pull/31
